% Test bench script for: My Vocal Enhancer.
% Generated by Audio Test Bench on 07-Jun-2025 13:08:35 UTC-04:00.

% Create test bench input and output
fileReader = dsp.AudioFileReader(Filename='C:\Users\ryanb\OneDrive\Documents\MATLAB\VAD HACKATHON\Noisy Speech.wav', ...
    PlayCount=6, ...
    SamplesPerFrame=512);
deviceWriter = audioDeviceWriter(SampleRate=fileReader.SampleRate);

% Create the objects under test
sut1 = voiceSuite;
setSampleRate(sut1,fileReader.SampleRate);

% Open parameter tuners for interactive tuning during simulation
tuner1 = parameterTuner(sut1);
drawnow

% Stream processing loop
nUnderruns = 0;
while ~isDone(fileReader)
    % Read from input, process, and write to output
    in = fileReader();
    out1 = sut1(in);
    nUnderruns = nUnderruns + deviceWriter(out1);

    % Process parameterTuner callbacks
    drawnow limitrate
end

% Clean up
release(sut1)
release(fileReader)
release(deviceWriter)
